out_dim: 1280
model: model6
esm2_15b:
    _target_: model.Model6
    in_dim: 5120
    hidden_dim1: 3145
    hidden_dim2: 2560
    out_dim: ${..out_dim}

esm2_650m:
    _target_: model.Model6
    in_dim: 1280
    hidden_dim: 1280
    out_dim: ${..out_dim}
