defaults:
    - _self_
    - data: trial-tvt 
    - models: model6
    - losses@Loss1: MarginLossFxn
    - losses@Loss2: BCElogitsLossFxn
    - distance_fn: sig_cos_d
    - anneal_fn: tanh_decay
    
wandb:
  group: 'TMLfrqupd_BCEless'

n_epochs: 20
lr: 0.000001
alternate_epochs: True 
n_alternate_epoch: 5
burn_in_epochs: 10
job_type: 'training'
project: 'trial2-biotin-${hydra:runtime.choices.models}'
seed: 123
